# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d17543e95699dccfd514dd4e7ee259adde29c33d5dcd30e24c3bf3f9772a0b45c72a995ddad14940738a31d91ad9c2b284dd0630e024758102c46456f6175a

test:
  secret_key_base: f8d333924e38ff738c183168932e22d87a81edb83a68e7d1ab7ddbae6b4abe8a0169d160679d5bd9068230f50d7e7f4844823267c58a34d3e5c343573c20f483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
